AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "db/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/DotPosition:
  EnforcedStyle: trailing

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20
