require "realms/cards/card"
require "realms/cards/scout"
require "realms/cards/viper"
require "realms/cards/explorer"
require "realms/cards/blob_fighter"
require "realms/cards/battle_pod"
require "realms/cards/trade_pod"
require "realms/cards/blob_wheel"
require "realms/cards/ram"
require "realms/cards/blob_destroyer"
require "realms/cards/the_hive"
require "realms/cards/battle_blob"
require "realms/cards/blob_carrier"
require "realms/cards/mothership"
require "realms/cards/blob_world"
require "realms/cards/federation_shuttle"
require "realms/cards/cutter"
require "realms/cards/embassy_yacht"
require "realms/cards/trading_post"
require "realms/cards/barter_world"
require "realms/cards/freighter"
require "realms/cards/defense_center"
require "realms/cards/trade_escort"
require "realms/cards/flagship"
require "realms/cards/port_of_call"
require "realms/cards/central_office"
require "realms/cards/command_ship"

module Realms
  module Cards
  end
end
